### ISSUE TITLE
Weak picking algorithm

### ISSUE THREAD

**Issue by marcbackes** [thinreports/thinreports-editor#1]
The algorithm for picking elements is week. With weak, I mean, if you for example have a line in a box, it it very hard to select the line. It always selects the box. A workaround is, zooming to a 1000%. Then it works.

If the language, ThinReports Editor is written in, does not allow better selecting, it would be a good compromise to have a list (maybe in the right bottom toolbar), to show all elements on the page. Similar to how Photoshop does it.

Because like the program works now, I lose more time on fiddling around with the graphical elements than actually writing code.

I would DEEPLY appreciate an improvement in this area.

**Comment by hidakatsuya** [comment]
I believe that this issue has been fixed in the latest version Editor, so i will close this issue. Feel free to reopen if you feel like your issue is not resolved.
