### ISSUE TITLE
Windowsのテーマをクラシックに設定するとテキストツールが正常に表示されない

### ISSUE THREAD

**Issue by Ayaka** [thinreports/thinreports-editor#11]
標題通りのバグがありましたので、issueを作成しました。

確認した環境
- Windows7(64bit)
- ThinReports Editor 0.7.7.2

ThinReportsEditor のテキストツールをキャンバス上に置き、
文字を入力して OK を押すと作成されたテキストフィールド内に文字が表示されません。

テキストフィールドの位置をずらしたり文字サイズを変更した結果、
入力した文字がテキストフィールドの左上の方に表示されていることが確認できました。

見えなかったのは左上過ぎて用紙外に表示されていたためです。

こちらで調べたところ、原因はWindowsテーマにあるようでした。

元々こちらの環境では「Windowsクラシック」をテーマにしていたのですが、
テーマを「Windows7 ベーシック」に変更したところ正常に表示されました。

また、テーマが「Windows7 ベーシック」の環境から、「Windowsクラシック」に変更すると入力文字が左上の方にずれるようになりました。

以上がバグの報告になります。

**Comment by maeda-m** [comment]
Closed by 3122ad74c5ecbf8febefe3dedaf0821de76bc24f
