### ISSUE TITLE
バージョン0.7.6　のtlfファイルを更新したいです

### ISSUE THREAD

**Issue by kotoyukihana** [thinreports/thinreports-editor#162]
リリースページのthinreport edita0.8.2のブラウザ版appが起動できないのですが、どのような対応を行えば良いでしょうか。

ブラウザでロゴが表示されたのち、デバックツールコンソールでエラー
「Uncaught TypeError: Cannot read properties of undefined (reading 'local')
    at app.js:326:1002
    at Array.reduce (<anonymous>)
    at jc (app.js:106:39)
    at Kl (app.js:326:975)
    at Jl (app.js:326:874)
    at Om (app.js:353:711)
    at app.js:842:188
    at p.handleEvent (app.js:140:1056)
    at Ie (app.js:148:274)
    at Ae (app.js:150:184)」が表示されます。

更新の目標バージョンは0.12.0です

**Comment by hidakatsuya** [comment]
v0.8.x 当時は Chromeアプリ版とデスクトップ版でリリースしていましたが、Chromeアプリ版については、2018年の Chromeアプリの廃止に伴い、すでに利用できなくなっています。ダウンロードされたのは、その Chromeアプリ版のソースコードだと思いますが、Chrome アプリ上でのみ動作するものですので、今となっては動かす方法はありません。

v0.8.0 のデスクトップ版が以下の Sourceforgeプロジェクト（当時のミラーサイト）からダウンロードできます。
https://sourceforge.net/projects/thinreports/files/

8年以上前のもので、現在の環境で利用できるかわかりませんが、もしこれが利用できるなら、以下の手順でアップグレードできるかもしれません。

1. v0.8.0 のデスクトップ版で tlf を開き上書き保存し、tlf の最終更新バージョンを 0.8.0 へ更新
2. https://github.com/hidakatsuya/thinreports-cli を使って、tlf を 0.9 フォーマットへ変換
3. 0.12.0 で開く

なお、これ以外の方法はわかりません。

**Comment by kotoyukihana** [comment]
夜分遅くの回答ありがとうございます。
ご教授いただいた方法を試してみます。

この方法ができない場合は、やはりv0.7.6 のtlfファイルをrails6 ruby3.0（thinreports v0.12.0）で使用するのは不可と考えてよろしいでしょうか？

**Comment by hidakatsuya** [comment]
> この方法ができない場合は、

はい、残念ながら難しいかもしれません。

なお、今後同様のご質問を投稿いただく際には、下記公式ディスカッションに投稿することをご検討ください。他の方の参考にもなるかもしれません。
https://github.com/orgs/thinreports/discussions

**Comment by kotoyukihana** [comment]
夜分遅くに回答ありがとうございます。
いただいたミラーサイトからwindows環境にて0.8.0を展開し、その後macにて0.12.0までバージョンアップさせることができました。大変感謝申し上げます。
公式ディスカッションへの投稿を行いたいと思います。
本当にありがとうございます。

**Comment by hidakatsuya** [comment]
では、こちら閉じますね。
