### ISSUE TITLE
Show confirmation dialog if there are unsaved files

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports-editor#23]
However, `window.onbeforeclose` is disabled in ChromeApp. In addition, ChromeApp provides `chrome.app.window.onClosed` event, but this event is not able to cancel before close.

https://developer.chrome.com/apps/app_window#event-onClosed

**Comment by maeda-m** [comment]
`onClosed` event is not the expect behavior.

**Comment by maeda-m** [comment]
Memo: `chrome.app.window.create` のオプションで `frame` というものがあり、それを `none` するとリサイズしかできなくなり、ウィンドウの移動もできなくなる。
ただし、UIとしてドラッグ可能な領域を用意してあげれば `frame:none` で良さそう。

**Comment by hidakatsuya** [comment]
@maeda-m 確かにそれで物理的な close は防止できるけど、例えば Mac で言えば `cmd+w` とか `cmd+q` での終了はスルーする（と思う）ので、それを考えるとあまり旨味はないかな。

**Comment by maeda-m** [comment]
@hidakatsuya ショートカットがありましたね。。。
ちょっとイベント無効化できるか試してみますね。

**Comment by maeda-m** [comment]
frameの案は却下。localStorageへ定期的にバックアップを取る手段にする。
強制終了した場合は次回起動時に確認ダイアログが表示され、復元できる。

**Comment by maeda-m** [comment]
TODO:
* ファイルを開いた直後など保存されたファイルから変更がない場合は、バックアップを取らない。
 * `HistoryManager` に変化があれば変更されたと判断する。

**Comment by maeda-m** [comment]
must to change `text_unsaved_layout_exists_confirmation` message

**Comment by maeda-m** [comment]
activeな状態でBackupされた一覧表が正しく復元できない。
inactiveな状態だときちんと復元できる。
