### ISSUE TITLE
Key-events dose not work with ChromeApp ver

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports-editor#26]
I confirmed that following key-events doesn't work:

  * Ctrl-V
  * Ctrl-C
  * Ctrl-X

I probably think that this problem will be caused by enabling key-events of ChromeApp.

**Comment by hidakatsuya** [comment]
@maeda-m 検証の結果、Mac の場合、これらのキーイベントは Command キーではなく Ctrl キーで正しく動作するようですが Command キーが正しいです。Closure Library を Update すれば解決しそうですが、それも難しいので、まずは現在のバージョンで解決できないか修正してみてください。

**Comment by hidakatsuya** [comment]
@maeda-m なので Ctrl-V/X/C だけではなく、 Ctrl-* はすべて Command キーでは動作しないです。

**Comment by maeda-m** [comment]
**KeyMap by Mac**

|Key                   |e.keyCode |e.ctrlKey |e.metaKey|
|--------------------|---------------|-----------|--------------|
|Left Command  |91              |false       |true           |
|Right Command|93              |false       |true           |
|Control              |17              |true        |false          |

**KeyMap by Win7**

|Key                   |e.keyCode |e.ctrlKey |e.metaKey|
|--------------------|---------------|-----------|--------------|
|Left Ctrl            |17              |true        |false          |
|Right Ctrl          |17              |true        |false          |

**Comment by maeda-m** [comment]
Handling of "Ctrl Key" and "Command Key" is different.

See [goog/events/keycodes.js](https://github.com/google/closure-library/blob/master/closure/goog/events/keycodes.js#L182)

**Comment by maeda-m** [comment]
Shortcut exists in Native Menu For Mac but operation is not considered.

See [sample/Copycat Window](https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/windows)
