### ISSUE TITLE
Wrong position of Text and caption of list section

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports-editor#27]
See below:

![text-position](https://cloud.githubusercontent.com/assets/739339/6317881/71693008-bab5-11e4-8ac2-25c66444ba61.png)

![caption-position](https://cloud.githubusercontent.com/assets/739339/6317882/7c409fa2-bab5-11e4-8c05-5d3a46271bca.png)

**Comment by maeda-m** [comment]
css can be solved even by adding, but the cause was wrong calculation method in the y-positoin of the Text.

```css
svg {
  position: relative;
}
```
