### ISSUE TITLE
Disable native context-menu in production

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports-editor#28]
However, it should enable in development.

**Comment by maeda-m** [comment]
`chrome.contextMenus.onClicked` is executed when click on the menu item.

**Comment by hidakatsuya** [comment]
@maeda-m どういう意味？ コンテキストメニューに標準のメニューは表示されてしまうけど `chrome.contextMenus.onClicked` によってメニュー自体の動作を無効にするアプローチを試してるってこと？

**Comment by maeda-m** [comment]
@hidakatsuya 
`onClicked` はコンテキストメニュー内のメニューをクリックすると実行されるイベントだよ。というメモです。
今のところ、コンテキストメニューの表示自体を無効化できなか調査中です。

**Comment by hidakatsuya** [comment]
@maeda-m Please check in your operation :smiley:
