### ISSUE TITLE
Character spacing display of the document(html) is different from the layout

### ISSUE THREAD

**Issue by maeda-m** [thinreports/thinreports-editor#36]
![layout-charactor-spacing](https://cloud.githubusercontent.com/assets/943541/7020218/3d20b64e-dd52-11e4-9c5a-52fb2155f3d5.png)
![spec-charactor-spacing](https://cloud.githubusercontent.com/assets/943541/7020219/40627c5c-dd52-11e4-8be6-38b3a386960a.png)

**Comment by maeda-m** [comment]
#38 でChrome版の文字間隔のプロパティを `kerning` から `letter-spacing` に変更したところ、
レイアウト定義(html)の文字間隔表示が正常になった。
しかし、Qt版は依然として `kerning` を使用しているため表示が異なる。

**Comment by hidakatsuya** [comment]
Qt version Editor has not been provided already. So i will close this issue.
