### ISSUE TITLE
Update documentations for 0.8.0

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports-editor#41]
- [x] CHANGELOG
- [x] README

**Comment by hidakatsuya** [comment]
@maeda-m "open source report generating" -> "open source report **generation**"

**Comment by maeda-m** [comment]
@hidakatsuya OK!

**Comment by maeda-m** [comment]
Closed #41 via dd51b71747458a0601a55e0110625295f7aeeb26
