### ISSUE TITLE
Does not resize the outline after updating content of the text in Property

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports-editor#42]
After updating in Toolbar works fine, but dose not work in Property.

![2015-04-21 0 10 13](https://cloud.githubusercontent.com/assets/739339/7233325/92d4e0ec-e7bb-11e4-93b9-e39d200933e9.png)

**Comment by maeda-m** [comment]
Closed via a24565d14d581dacbf7f0badb8a9bc3e59ee5b0f
