### ISSUE TITLE
Google Chrome on Ubuntu 14.10 Not run 

### ISSUE THREAD

**Issue by obelich** [thinreports/thinreports-editor#45]
Hiyas i have install the editor in Google chrome and next i click to run it apper the splash but dont do naffin more :(

Sorry me english is bad
![captura de pantalla de 2015-05-01 18 40 12](https://cloud.githubusercontent.com/assets/278037/7439465/b7badece-f031-11e4-8fbc-a0dc2fec9351.png)

**Comment by hidakatsuya** [comment]
@obelich Thank you for your reporting. We will confirm it.

**Comment by maeda-m** [comment]
Hi @obelich .

I was able to run the Thinreports in Ubuntu 14.10 (on VirtualBox). Therefore, Please tell me the results of try next two thing.

1) Look at the error log by the following procedure.
![procedure_error_log](https://cloud.githubusercontent.com/assets/943541/7510679/b99ea912-f4d9-11e4-9cb5-5381d162a220.png)

2) Disable all the Chrome Extensions, Launch the Thinreports Editor.

**Comment by obelich** [comment]
Same result no errors in console but not run :( i desable all the extensions but give the same not run
![captura de pantalla de 2015-05-07 08 01 12](https://cloud.githubusercontent.com/assets/278037/7518359/42d8c438-f48f-11e4-827f-3e49fcab6913.png)

**Comment by maeda-m** [comment]
@obelich Thank you for letting me know.
I'll try examined this issue in detail. Therefore, please wait a little more response.

**Comment by brunofrank** [comment]
I get the same in Windows and Linux.
![captura de tela de 2015-05-15 10_01_00](https://cloud.githubusercontent.com/assets/40139/7653075/745b3814-fae9-11e4-85bc-e9046b2034b5.png)

**Comment by maeda-m** [comment]
@brunofrank Thank you for your reporting.

I was able to reproduce the bug in my virtual environment.
If Chrome's language setting is other than English or Japanese, Editor does not work correctly.

This bug will be resolved the near future.

**Comment by brunofrank** [comment]
Works fine here, thank you!
