### ISSUE TITLE
Translate to Brazilian Portuguese

### ISSUE THREAD

**Issue by iskailer** [thinreports/thinreports-editor#49]
I created a pull request concerning translation editor for Brazilian Portuguese, but did not know if correct, would like to rate the translation and then instruct me how to share with all the translation.

**Comment by maeda-m** [comment]
@iskailer Thank you for your feedback.
How to translation and its confirmation, please refer to the [doc/TRANSLATION.md](https://github.com/thinreports/thinreports-editor/blob/master/doc/TRANSLATION.md) .
