### ISSUE TITLE
Too small font in ThinreportEditor on Surface Pro 3

### ISSUE THREAD

**Issue by mototaker** [thinreports/thinreports-editor#50]
![tr](https://cloud.githubusercontent.com/assets/10150818/8019759/b6275798-0c99-11e5-94ea-2fd893f157dd.JPG)

I use a Surface Pro 3 , and I use ThinreportEditor on Surface Pro 3.

Surface Pro 3 is 2160 x 1440.

Therefore the font is too small.

Please check it out.

**Comment by mototaker** [comment]
My version of ThinreportEditor is 0.8.0

![tre](https://cloud.githubusercontent.com/assets/10150818/8019769/2beb371a-0c9a-11e5-9802-ad1a1b50482b.JPG)

**Comment by hidakatsuya** [comment]
@mototaker Can you check whether ChromeApp ver has the same issue in your same environment?

**Comment by hidakatsuya** [comment]
Any other response? I will close this issue. Feel free to reopen this issue if you need.
