### ISSUE TITLE
Unexpected new line after hyphen

### ISSUE THREAD

**Issue by sozuuuuu** [thinreports/thinreports-editor#57]
I looked around the docs and couldn't find the solution.

### Problem

I render the text below.

```
report.page.item(:text).value <<TEXT
行く川のながれは絶えずして、-しかも本の水にあらず。よどみに浮ぶうたかたは、かつ消えかつ結びて久しくとゞまることなし。世の中にある人とすみかと、またかくの如し。玉しきの都の中にむねをならべいらかをあらそへる、たかきいやしき人のすまひは、代々を經て盡きせぬものなれど、これをまことかと尋ぬれば、昔ありし家はまれなり。
TEXT
```

The generated pdf contains unexpected new line after hyphen.

![2016-03-24 12 11 50](https://cloud.githubusercontent.com/assets/5513797/14007394/a6fd0e7e-f1b9-11e5-9100-da81693f58cc.png)

#### Configuration (text block tool)

![2016-03-24 12 13 58](https://cloud.githubusercontent.com/assets/5513797/14007433/014c298c-f1ba-11e5-83c5-d807f4ce7796.png)

**Comment by hidakatsuya** [comment]
@sozuuuuu Thank you for your reporting. I have moved this issue to thinreports/thinreports-generator/issues because the case of this issue is due to thinreports-generator.

**Comment by hidakatsuya** [comment]
@sozuuuuu Moved: thinreports/thinreports-generator#50
