### ISSUE TITLE
Is it possible to convert it to web app?

### ISSUE THREAD

**Issue by artemv** [thinreports/thinreports-editor#58]
First, thank you guys for a great product.

This is rather a question, not an issue.

It would be really useful for me to have the thinreports-editor available as plain web app, and possibly it's not very hard to do that provided that it's mostly Javascript.

What do you think? What would it require to do that? Any blockers, hidden stones?

**Comment by maeda-m** [comment]
@artemv 

If implement the behavior of  [platform/*.js](https://github.com/thinreports/thinreports-editor/tree/master/src/app/base/platform) in the browser, thinreports-editor is expected to be in the near future, plain web apps.

Previously, provides thinreports-editor in the original browser that was created in [Qt](https://www.qt.io/).
Currently, it has moved the platform from the original browser to [ChromeApps](https://developer.chrome.com/apps/about_apps).

Note:  ChromeApps has no [API](https://developer.chrome.com/apps/api_index) to GoogleChrome.

**Comment by maeda-m** [comment]
@artemv Please ask a question in [Google Group](https://groups.google.com/forum/?hl=ja#!forum/thinreports) from next time.

**Comment by hidakatsuya** [comment]
Any other response? I will close this issue. Feel free to reopen if you need.
