### ISSUE TITLE
Thinreports Editor 0.9.0 で古い形式のTLFファイルを開くと、レイアウトが崩れてしまう

### ISSUE THREAD

**Issue by maeda-m** [thinreports/thinreports-editor#60]
* https://groups.google.com/forum/?hl=ja#!topic/thinreports/KMz111C-xjM
* https://groups.google.com/d/msg/thinreports/BcKlJVlXtFY/ZrqymTb1BAAJ
* #61 

0.8.2 で作成した tlf を 0.9.0 で開くと List （一覧表）内に描画された Line （線形図形）が Translate 分ズレる。

**Comment by hidakatsuya** [comment]
@maeda-m 

こちらで報告された問題と同じ原因と思われる。
https://groups.google.com/d/msg/thinreports/BcKlJVlXtFY/ZrqymTb1BAAJ

上記に添付されている tlf を開いて、Report title などを編集し保存するたびに、リスト内の全 line の x2 が +11.7px されることを確認した。「ある時からこうなった」とのことだが、おそらくそれは 0.8.2 to 0.9.0 へアップデートした時だと思われる。

また #61 これも同じ原因だと思う。

**Comment by hidakatsuya** [comment]
Fixed by #62
