### ISSUE TITLE
レイアウトが全て表示されない

### ISSUE THREAD

**Issue by kntmrkm** [thinreports/thinreports-editor#61]
こんにちは。
以下の環境で利用させていただいています。

OSX 10.11.5
Chrome バージョン 51.0.2704.103 (64-bit)
Rails 
gem thinreports-0.9.1

レウアウトで設定している実線等がすべて表示されません。

![shipping](https://cloud.githubusercontent.com/assets/2703486/16714045/c6ac2e10-46f2-11e6-84d2-6f9a3a911b8f.png)

レイアウトは以下の状態です。
<img width="934" alt="thinreports_editor" src="https://cloud.githubusercontent.com/assets/2703486/16714049/d7ba7da6-46f2-11e6-816d-0b736f340a4a.png">

余白はすべて10pxで設定しています。

**Comment by kntmrkm** [comment]
![shipping](https://cloud.githubusercontent.com/assets/2703486/16714072/7acc79c2-46f3-11e6-98b7-b5a83eb173b8.png)
動的にセットする項目は切れることなく表示されるようです。

**Comment by hidakatsuya** [comment]
This issue is related to #60 .

**Comment by yuuna** [comment]
こちらのissueですが、かなりcriticalで修正見通しはいかがでしょうか
（Chrome Pluginが自動アップデートになりちょっと惨事です）

**Comment by hidakatsuya** [comment]
@yuuna 現在、最優先で対応を進めてます。自動アップデートについても重大な問題と認識していて、ChromeApp をやめて別のプラットホームに移行することも視野に対応を考えているところです。

**Comment by hidakatsuya** [comment]
Fixed by #62

**Comment by hidakatsuya** [comment]
@kntmrkm @yuuna 0.9.1 リリースしましたのでよろしければご確認ください。

**Comment by kntmrkm** [comment]
@hidakatsuya 
修正ありがとうございます。
0.9.1で編集・保存してみましたが変わりません。
実線オブジェクトを作り直し等必要ですか？

**Comment by hidakatsuya** [comment]
@kntmrkm はい、残念ながら既にずれてしまった罫線は元に戻らないので修正が必要です。

**Comment by kntmrkm** [comment]
@hidakatsuya 
□の罫線オブジェクトを一度削除して作りなおしても切れたままなのですが、ファイルからの作り直しですか？

**Comment by kntmrkm** [comment]
一覧表も作りなおしみたいですね。

**Comment by kntmrkm** [comment]
実線等というのは
https://cloud.githubusercontent.com/assets/2703486/16714045/c6ac2e10-46f2-11e6-84d2-6f9a3a911b8f.png

この画像の右端の「テ」、と四角の実線の２つ目です。
0.9.1に上げる前に、「テスト」という文字列はすべて表示されるようになり、実線のオブジェクト（行の罫線）は右端がすべて表示されませんでした。

先ほど、0.9.1で一覧表から作りなおしたところすべて表示されるようになりました。

**Comment by hidakatsuya** [comment]
> 0.9.1に上げる前に、「テスト」という文字列はすべて表示されるようになり、実線のオブジェクト（行の罫線）は右端がすべて表示されませんでした。

なるほど。おそらく、これは #60 とは別の原因です。過去にも一度だけありましたが、リストが何らかの原因で壊れてしまったためだと思います。その際も、結局リストを作り直して解決しましたが原因は不明なままです。引き続き、調査はしますがレアケースで再現方法がわからないので解決は難しいかもしれません。

**Comment by kntmrkm** [comment]
承知しました。
罫線の一覧表作るときはレイアウトを先に作ってしまって表示されることを確認してから作ります。
