### ISSUE TITLE
Changing the scale(zoom) causes changing the layout.

### ISSUE THREAD

**Issue by urimaro** [thinreports/thinreports-editor#64]
### Steps to reproduce
1. open the tlf file.
2. change the zoom parameter

Please see the gif animation below.
https://gyazo.com/ca5594c58a5959bb7bc4484c0978e99e
### Actual behavior

I think the text area isn't zooming up or out when the zoom parameter has been changed.
### System configuration

**Chrome version: 53.0.2785.116 (64bit)**
**Thinreports editor version: 0.9.1**

**Comment by maeda-m** [comment]
@urimaro 

I do not know for sure until you check the setting of the text, but I think the layout is zoom state is correct as a display.

Please show me the tlf file to be permissible.

**Comment by hidakatsuya** [comment]
I will close this issue. Feel free to reopen if you feel like your issue is not resolved.
