### ISSUE TITLE
This layout file cannot be opened because has problem

### ISSUE THREAD

**Issue by retorquere** [thinreports/thinreports-editor#70]
I'm trying to generate a template (https://gist.github.com/daf411f44f21d0ff357dba621dc183db) that could be further edited using thinreports editor, but when I load it I get a popup that says

> This layout file cannot be opened because has problem

How can I find out what problem it has?

**Comment by maeda-m** [comment]
Hello @retorquere 

I saw the contents of the file. There is a problem with the structure of details items.
For the structure of items, you can refer to [Spec: Layout File: Format](https://github.com/thinreports/thinreports/wiki/Spec%3A-Layout-File%3A-Format).

Thanks!

**Comment by retorquere** [comment]
Cool -- thanks! It was the extra array wrapper I was generating. Works now!

**Comment by retorquere** [comment]
(BTW as a suggestion: if a [JSON schema](https://json-schema.org/) could be constructed for TR layouts, [AJV](https://github.com/epoberezkin/ajv) could quickly check validity and would report exactly what was wrong)

**Comment by retorquere** [comment]
https://gist.github.com/8bc70d4dab521f7d0d36beba54131f1a should be close to a schema for tlf files.

**Comment by retorquere** [comment]
Slight simplification of the `report` properties: https://gist.github.com/f5cfb354fa72406b430fc0925a1f480b

**Comment by retorquere** [comment]
Some of the examples don't validate against [Spec: Layout File: Format](https://github.com/thinreports/thinreports/wiki/Spec%3A-Layout-File%3A-Format) because they have (empty) strings for number fields. [This](https://gist.github.com/baee535db940e15151c296e80e418f3a) version of the AJV schema allows for empty strings in number fields. The simplest validation is just

```
var fs = require('fs')
var Ajv = require('ajv');
var ajv = new Ajv();

var schema = require('./schema.json')
var data = JSON.parse(fs.readFileSync('estimate.tlf', 'utf-8'))
var validate = ajv.compile(schema);
if (!validate(data)) console.log(validate.errors)
```

but if you want a little more detail on where the error lies this has been helpful to me:

```
var fs = require('fs')
var Ajv = require('ajv');
var ajv = new Ajv();

var schema = require('./schema.json')
var data = JSON.parse(fs.readFileSync('estimate.tlf', 'utf-8'))

function validate(schema, layout) {
  let _validate = ajv.compile(schema);
  if (_validate(layout)) return {}
  const errors = _validate.errors

  for (const [i, item] of layout.items.entries()) {
    _validate = ajv.compile({...schema.definitions[item.type], definitions: schema.definitions});
    if (!_validate(item)) return { item: i, errors: _validate.errors }
  }

  return { layout: true, errors }
}

console.log(validate(schema, data))
```

With this, feedback can be provided to the user by detailing where the error occurs.
