### ISSUE TITLE
レイアウトが見切れる

### ISSUE THREAD

**Issue by toney-skm** [thinreports/thinreports-editor#73]
現在以下の環境で検証しています。
OS： Windows10
ブラウザ：Internet Explorer11,Microsoft Edge
Ruby：2.3.3
Rails：4.2.11
thinreports：0.10.3
thinreports-editor ：1.6.11

最新のエディタを利用して新しく帳票を作成した際に、一覧表ツール内で、
作成したテキストツールなどの画面左側部分が見切れます。
(ブロックツールについては見切れません)

<ソースコード>
`report = Thinreports::Report.new :layout => File.join(Rails.root, 'reports', 'test.tlf') 
report.start_new_page 　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
report.list.header.values :today => Date.today 　　　　　　　　　　　　　　　　　　　　　　
send_data report.generate, :filename    => 'filekizyunsoukatuhyou.pdf',  :type=> 'application/pdf',  :disposition => 'attachment'`

<帳票レイアウト>
![キャプチャ](https://user-images.githubusercontent.com/39107018/66362467-de595d00-e9bd-11e9-89aa-8d6a36bb390c.PNG)
<出力結果>
![キャプ2チャ](https://user-images.githubusercontent.com/39107018/66362475-e6190180-e9bd-11e9-802d-fd90aeb5c1ef.PNG)

現在ほぼ上記現象が発生しています(1回のみ見切れない帳票を作成出来た)
ブロックツールを作成するタイミングや配置について、
何パターンか試していますが、見切れる範囲が変更されるのみで、
改善されませんでした。
余白の変更でも改善されません。

現象としては以下のIssuesと同じものだと考えています。
[https://github.com/thinreports/thinreports-editor/issues/61](url)
上記Issuesについては、最終的な原因が特定できていないため、
改善方法を教えてください。

**Comment by hidakatsuya** [comment]
@maeda-m 何かわかりますか？

**Comment by hidakatsuya** [comment]
> thinreports-editor ：1.6.11

一つ確認です。上記のようなバージョンの Editor はありませんので再度確認をお願いします。現在の最新は下記にある通り 0.10.0 となります。
https://github.com/thinreports/thinreports-editor/releases

**Comment by toney-skm** [comment]
@hidakatsuya
Editorのバージョンは0.10.0でした。
インストールしたファイルの中にversionというファイルがあり、
そこにv1.6.11との記述があったので、勘違いしてしました。
失礼しました。

**Comment by toney-skm** [comment]
一覧表ツールを利用して、サイズの小さい一覧表を作成した後、
基本設定から幅や高さを大きくした場合に、
今回のような見切れる事象が発生することがわかりました。
想定しているサイズよりも大きいサイズの一覧表を作成した後、
基本設定から幅や高さを調整することで、一応対応することが可能でした。
