### ISSUE TITLE
Move code for basic report editor to basic-report/

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports-editor#94]
コードベースのディレクトリ構成を次のようにする。

## basic-report/

従来の Editor のコードを配置するディレクトリ。 section-report テンプレートフォーマットに対して、basic-report フォーマットと呼称する。

## section-report/

https://github.com/thinreports/thinreports-editor/pull/87 で追加された Editor のコードを配置するディレクトリ。この Editor は、新しいテンプレートフォーマット section-report フォーマットを編集する。

この構成変更に伴い、以下の対応も実施する。

- ルートの README.md で上記2つの Editor を説明する
- `section_report/` ディレクトリを `section-report/` へ名称変更

以下はあとで実施する。

- section-report の README.md を作成

**Comment by hidakatsuya** [comment]
大きな差分だったので 03f198a3d5bbd60da038ded2ea24b74fbee35138 とその後のコミットで既に master に反映済み。

@maeda-m 事後連絡ですが、上記のように対応しました。気づいた点などがあれば教えてください。

**Comment by maeda-m** [comment]
@hidakatsuya 対応ありがとうございます。

連絡が遅くなりました。特に気になるところはありませんでした。

なお、差分はディレクトリの移動がほとんどだと確認しましたが、
念のため Windows 10 + Node.js 14 の環境で、section-report と basic-report がビルドできることを確認しました。

**Comment by hidakatsuya** [comment]
確認ありがとうございます。こちらはクローズしますね。
